version: '3.1'

services:
  db:
    build: docker-mariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      timeout: 5s
      interval: 10s
      retries: 20
    volumes: 
      - "./db-data:/var/lib/mysql"
    networks:
      - internal_network
  wildfly:
    build:
      context: docker-wildfly
      args:
        WILDFLY_USERNAME: "${WILDFLY_USERNAME}"
        WILDFLY_PASSWORD: "${WILDFLY_PASSWORD}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER_MOK: "${MYSQL_USER_MOK}"
        MYSQL_PASSWORD_MOK: "${MYSQL_PASSWORD_MOK}"
        MYSQL_USER_MOB: "${MYSQL_USER_MOB}"
        MYSQL_PASSWORD_MOB: "${MYSQL_PASSWORD_MOB}"
        MYSQL_USER_MOL: "${MYSQL_USER_MOL}"
        MYSQL_PASSWORD_MOL: "${MYSQL_PASSWORD_MOL}"
        MYSQL_USER_AUTH: "${MYSQL_USER_AUTH}"
        MYSQL_PASSWORD_AUTH: "${MYSQL_PASSWORD_AUTH}"
    image: wildfly
    restart: always
    expose:
      - "8080"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"
    depends_on:
            db:
              condition: service_healthy
    environment:
      - WLP_LOGGING_CONSOLE_LOGLEVEL
      - WLP_LOGGING_CONSOLE_SOURCE
    networks:
      - internal_network
  nginx:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - internal_network
      - public_network
    depends_on:
      - wildfly
    restart: always

networks:
  internal_network:
    internal: true
  public_network:
    driver: bridge
