version: '3.1'

services:
  db:
    build: docker-mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssbd04
      MYSQL_USER: ssbd04
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ssbd04
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  wildfly:
    build:
      context: docker-wildfly
      args:
        WILDFLY_USERNAME: admin
        WILDFLY_PASSWORD: ssbd04
    image: wildfly
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"
