version: '3.1'

services:
  db:
    build: docker-mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssbd04
      MYSQL_USER: ssbd04
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ssbd04
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "ssbd04", "-p12345678"]
      timeout: 5s
      interval: 10s
      retries: 20
  openliberty:
    build:
      context: docker-openliberty
    image: openliberty
    restart: always
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - "./deployments:/config/dropins"
    depends_on:
      db:
        condition: service_healthy
    environment:
      WLP_LOGGING_CONSOLE_LOGLEVEL: info
      WLP_LOGGING_CONSOLE_SOURCE: message,trace,accessLog,ffdc,audit
