version: '3.1'

services:
  db:
    build: docker-mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssbd04
      MYSQL_USER: ssbd04
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: ssbd04
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-u", "ssbd04", "-p12345678"]
      timeout: 5s
      interval: 10s
      retries: 20
  openliberty:
    build:
      context: docker-wildfly
      args:
        WILDFLY_USERNAME: admin
        WILDFLY_PASSWORD: ssbd04
    image: wildfly
    restart: always
    ports:
      - "9990:9990"
      - "8080:8080"
      - "8443:8443"
      - "8787:8787"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"
      # - "./docker-wildfly/configuration:/opt/jboss/wildfly/standalone/configuration"
    depends_on:
            db:
                    condition: service_healthy
    environment:
      WLP_LOGGING_CONSOLE_LOGLEVEL: info
      WLP_LOGGING_CONSOLE_SOURCE: message,trace,accessLog,ffdc,audit
