version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssbd04
  wildfly:
    build:
      context: .
      args:
        WILDFLY_USERNAME: admin
        WILDFLY_PASSWORD: ssbd04
    image: wildfly
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"
