export const ACTION_LOGIN_BEGIN = 'LOGIN_BEGIN';
export const ACTION_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ACTION_LOGIN_FAILURE = 'LOGIN_FAILURE';
export const ACTION_LOGOUT = 'LOGOUT';
export const ACTION_CHANGE_ROLE = 'CHANGE_ROLE';
export const ACTION_GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
export const ACTION_GET_ALL_ACCOUNTS_FAILURE = 'GET_ALL_ACCOUNTS_FAILED';
export const ACTION_GET_ALL_ACCOUNTS_BEGIN = 'GET_ALL_ACCOUNTS_BEGIN';
