--AccountDetails

CREATE TABLE account_details
(
    id          bigint       NOT NULL
        CONSTRAINT account_details_pkey PRIMARY KEY,
    email       varchar(255) NOT NULL
        CONSTRAINT account_details_email UNIQUE,
    first_name   varchar(30)  NOT NULL,
    last_name    varchar(30)  NOT NULL,
    phone_number varchar(15)  NOT NULL,
    VERSION     bigint
);


ALTER TABLE account_details
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON account_details TO ssbd04mok;

GRANT
    SELECT ON account_details TO ssbd04mol;

GRANT
    SELECT ON account_details TO ssbd04mob;

CREATE SEQUENCE account_details_seq
    START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE CACHE 1;


ALTER SEQUENCE account_details_seq OWNER TO ssbd04admin;

GRANT
    USAGE, SELECT ON account_details_seq TO ssbd04mok;

GRANT
    SELECT ON account_details_seq TO ssbd04mob;

SELECT pg_catalog.setval('account_details_seq', 1, FALSE);


--Account

CREATE TABLE account
(
    id                 bigint      NOT NULL
        CONSTRAINT account_pkey PRIMARY KEY,
    active             boolean     NOT NULL,
    confirm            boolean     NOT NULL,
    login              varchar(30) NOT NULL
        CONSTRAINT account_login_unique UNIQUE,
    password           varchar(60) NOT NULL,
    VERSION            bigint,
    account_details_id bigint
        CONSTRAINT account_account_details_id_unique UNIQUE
        CONSTRAINT account_account_details_id_fkey REFERENCES account_details
);


ALTER TABLE account
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON account TO ssbd04mok;

GRANT
    SELECT ON account TO ssbd04mol;

GRANT
    SELECT ON account TO ssbd04auth;

GRANT
    SELECT ON account TO ssbd04mob;


CREATE SEQUENCE account_seq
    START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE CACHE 1;


ALTER SEQUENCE account_seq OWNER TO ssbd04admin;

GRANT
    USAGE, SELECT ON account_seq TO ssbd04mok;

GRANT
    SELECT ON account_seq TO ssbd04mob;


SELECT pg_catalog.setval('account_seq', 1, FALSE);

--AccountAccessLevel

CREATE TABLE account_access_level
(
    access_level varchar(31) NOT NULL,
    id           bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME account_access_level_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT account_access_level_pkey PRIMARY KEY,
    VERSION      bigint,
    account_id   bigint
        CONSTRAINT account_access_level_account_fkey REFERENCES account
);


ALTER TABLE account_access_level
    OWNER TO ssbd04admin;


ALTER SEQUENCE account_access_level_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON account_access_level TO ssbd04mok;

GRANT
    SELECT ON account_access_level TO ssbd04mol;

GRANT
    SELECT ON account_access_level TO ssbd04mob;

GRANT
    SELECT ON account_access_level TO ssbd04auth;

GRANT
    USAGE, SELECT ON account_access_level_id_seq TO ssbd04mok;

GRANT
    SELECT ON account_access_level_id_seq TO ssbd04mob;


SELECT pg_catalog.setval('account_access_level_id_seq', 1, FALSE);

--AirPlaneSchema

CREATE TABLE airplane_schema
(
    id      bigint GENERATED BY DEFAULT AS identity
        (SEQUENCE NAME airplane_schema_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT airplane_schema_pkey PRIMARY KEY,
    cols    integer NOT NULL
        CONSTRAINT airplane_schema_cols_check CHECK (cols >= 1),
    ROWS    integer NOT NULL
        CONSTRAINT airplane_schema_rows_check CHECK (ROWS >= 1),
    VERSION bigint
);


ALTER TABLE airplane_schema
    OWNER TO ssbd04admin;


ALTER SEQUENCE airplane_schema_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON airplane_schema TO ssbd04mol;

GRANT
    SELECT ON airplane_schema TO ssbd04mok;

GRANT
    SELECT ON airplane_schema TO ssbd04mob;

GRANT
    USAGE, SELECT ON airplane_schema_id_seq TO ssbd04mol;

GRANT
    SELECT ON airplane_schema_id_seq TO ssbd04mob;


SELECT pg_catalog.setval('airplane_schema_id_seq', 1, FALSE);

--Aiport

CREATE TABLE airport
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME airport_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT airport_pkey PRIMARY KEY,
    city    varchar(32)  NOT NULL,
    code    varchar(255) NOT NULL,
    country varchar(32)  NOT NULL,
    name    varchar(32)  NOT NULL,
    VERSION bigint
);


ALTER TABLE airport
    OWNER TO ssbd04admin;


ALTER SEQUENCE airport_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON airport TO ssbd04mol;

GRANT
    SELECT ON airport TO ssbd04mok;

GRANT
    SELECT ON airport TO ssbd04mob;

GRANT
    USAGE, SELECT ON airport_id_seq TO ssbd04mol;

GRANT
    SELECT ON airport_id_seq TO ssbd04mob;


SELECT pg_catalog.setval('airport_id_seq', 1, FALSE);

--Connection

CREATE TABLE CONNECTION
(
    id             bigint GENERATED BY DEFAULT AS identity
        (SEQUENCE NAME connection_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT connection_pkey PRIMARY KEY,
    base_price      numeric(9, 2) NOT NULL,
    VERSION        bigint,
    destination_id bigint        NOT NULL
        CONSTRAINT connection_destination_id_fkey REFERENCES airport,
    source_id      bigint        NOT NULL
        CONSTRAINT connection_source_id_fkey REFERENCES airport
);


ALTER TABLE CONNECTION
    OWNER TO ssbd04admin;


ALTER SEQUENCE connection_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON CONNECTION TO ssbd04mol;

GRANT
    SELECT ON CONNECTION TO ssbd04mok;

GRANT
    SELECT ON CONNECTION TO ssbd04mob;

GRANT
    USAGE, SELECT ON connection_id_seq TO ssbd04mol;
GRANT
    SELECT ON connection_id_seq TO ssbd04mob;


SELECT pg_catalog.setval('connection_id_seq', 1, FALSE);

--Flight

CREATE TABLE flight
(
    id                 bigint        NOT NULL
        CONSTRAINT flight_pkey PRIMARY KEY,
    end_date_time        TIMESTAMP     NOT NULL,
    flight_code         varchar(30)   NOT NULL
        CONSTRAINT flight_flightcode_unique UNIQUE,
    price              numeric(9, 2) NOT NULL,
    status             varchar(64)   NOT NULL,
    start_date_time      TIMESTAMP     NOT NULL,
    VERSION            bigint,
    airplane_schema_id bigint        NOT NULL
        CONSTRAINT flight_airplane_schema_id_fkey REFERENCES airplane_schema,
    connection_id      bigint        NOT NULL
        CONSTRAINT flight_connection_id_fkey REFERENCES CONNECTION
);


ALTER TABLE flight
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON flight TO ssbd04mol;

GRANT
    SELECT ON flight TO ssbd04mok;

GRANT
    SELECT ON flight TO ssbd04mob;


CREATE SEQUENCE flight_seq
    START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE CACHE 1;


ALTER SEQUENCE flight_seq OWNER TO ssbd04admin;

GRANT
    USAGE, SELECT ON flight_seq TO ssbd04mol;

GRANT
    SELECT ON flight_seq TO ssbd04mob;


SELECT pg_catalog.setval('flight_seq', 1, FALSE);

--Benefit

CREATE TABLE benefit
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME benefit_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT benefit_pkey PRIMARY KEY,
    description varchar(255) NOT NULL,
    name        varchar(128) NOT NULL,
    VERSION     bigint
);


ALTER TABLE benefit
    OWNER TO ssbd04admin;


ALTER SEQUENCE benefit_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON benefit TO ssbd04mob;

GRANT
    SELECT ON benefit TO ssbd04mok;

GRANT
    SELECT ON benefit TO ssbd04mol;

GRANT
    USAGE, SELECT ON benefit_id_seq TO ssbd04mob;

GRANT
    SELECT ON benefit_id_seq TO ssbd04mol;

SELECT pg_catalog.setval('benefit_id_seq', 1, FALSE);

--SeatClass

CREATE TABLE seat_class
(
    id      bigint GENERATED BY DEFAULT AS identity
        (SEQUENCE NAME seat_class_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT seat_class_pkey PRIMARY KEY,
    name    varchar(30)   NOT NULL
        CONSTRAINT seat_class_name_unique UNIQUE,
    price   numeric(9, 2) NOT NULL,
    VERSION bigint
);


ALTER TABLE seat_class
    OWNER TO ssbd04admin;


ALTER SEQUENCE seat_class_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON seat_class TO ssbd04mob;

GRANT
    SELECT ON seat_class TO ssbd04mok;

GRANT
    SELECT ON seat_class TO ssbd04mol;

GRANT
    USAGE, SELECT ON seat_class_id_seq TO ssbd04mob;

GRANT
    SELECT ON seat_class_id_seq TO ssbd04mol;


SELECT pg_catalog.setval('seat_class_id_seq', 1, FALSE);

--Seat

CREATE TABLE seat
(
    id            bigint GENERATED BY DEFAULT AS identity
        (SEQUENCE NAME seat_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)
        CONSTRAINT seat_pkey PRIMARY KEY,
    col           integer NOT NULL,
    number        integer NOT NULL,
    ROW           integer NOT NULL,
    VERSION       bigint,
    seat_class_id bigint  NOT NULL
        CONSTRAINT seat_seat_class_id_fkey REFERENCES seat_class,
    airplane_schema_id     bigint  NOT NULL
        CONSTRAINT seat_schema_id_fkey REFERENCES airplane_schema
);


ALTER TABLE seat
    OWNER TO ssbd04admin;


ALTER SEQUENCE seat_id_seq OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON seat TO ssbd04mob;

GRANT
    SELECT ON seat TO ssbd04mok;

GRANT
    SELECT ON seat TO ssbd04mol;

GRANT
    USAGE, SELECT ON seat_id_seq TO ssbd04mob;

GRANT
    SELECT ON seat_id_seq TO ssbd04mol;


SELECT pg_catalog.setval('seat_id_seq', 1, FALSE);

--Ticket

CREATE TABLE ticket
(
    id         bigint        NOT NULL
        CONSTRAINT ticket_pkey PRIMARY KEY,
    total_price numeric(9, 2) NOT NULL,
    VERSION    bigint,
    account_id bigint        NOT NULL
        CONSTRAINT ticket_account_id_fkey REFERENCES account,
    flight_id  bigint        NOT NULL
        CONSTRAINT ticket_flight_id_fkey REFERENCES flight
);


ALTER TABLE ticket
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON ticket TO ssbd04mob;

GRANT
    SELECT ON ticket TO ssbd04mok;

GRANT
    SELECT ON ticket TO ssbd04mol;


CREATE SEQUENCE ticket_seq
    START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE CACHE 1;


ALTER SEQUENCE ticket_seq OWNER TO ssbd04admin;

GRANT
    USAGE, SELECT ON ticket_seq TO ssbd04mob;


SELECT pg_catalog.setval('ticket_seq', 1, FALSE);

--Passenger

CREATE TABLE passenger
(
    id          bigint       NOT NULL
        CONSTRAINT passenger_pkey PRIMARY KEY,
    email       varchar(255) NOT NULL
        CONSTRAINT passenger_email UNIQUE,
    first_name   varchar(30)  NOT NULL,
    last_name    varchar(30)  NOT NULL,
    phone_number varchar(15)  NOT NULL,
    ticket_id   bigint       NOT NULL
        CONSTRAINT ticket_id_fkey REFERENCES ticket,
    seat_id     bigint       NOT NULL
        CONSTRAINT seat_id_fkey REFERENCES seat,
    VERSION     bigint
);


ALTER TABLE passenger
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON passenger TO ssbd04mob;

GRANT
    SELECT ON passenger TO ssbd04mok;

GRANT
    SELECT ON passenger TO ssbd04mol;


CREATE SEQUENCE passenger_seq
    START WITH 1 INCREMENT BY 10 NO MINVALUE NO MAXVALUE CACHE 1;


ALTER SEQUENCE passenger_seq OWNER TO ssbd04admin;

GRANT
    USAGE, SELECT ON passenger_seq TO ssbd04mob;


SELECT pg_catalog.setval('passenger_seq', 1, FALSE);

--SeatClass <-> Benefit

CREATE TABLE seat_class_benefits
(
    seat_class_id bigint NOT NULL
        CONSTRAINT seat_class_benefits_seat_class_id_fkey REFERENCES seat_class,
    benefit_id    bigint NOT NULL
        CONSTRAINT seat_class_benefits_benefit_id_fkey REFERENCES benefit,
    CONSTRAINT seat_class_benefits_pkey PRIMARY KEY (seat_class_id,
                                                     benefit_id)
);


ALTER TABLE seat_class_benefits
    OWNER TO ssbd04admin;

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE ON seat_class_benefits TO ssbd04mob;

GRANT
    SELECT ON seat_class_benefits TO ssbd04mok;

GRANT
    SELECT ON seat_class_benefits TO ssbd04mol;